steps:
  # 1) Docker-Image bauen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA', '.']

  # 2) Docker-Image taggen
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'tag',
      'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA',
      'gcr.io/$PROJECT_ID/lion-astro-app:latest'
    ]

  # 3) Docker-Image pushen (SHA)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA']

  # 4) Docker-Image pushen (latest)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lion-astro-app:latest']

images:
  - 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/lion-astro-app:latest'

options:
  # Nur Cloud Logging (kein GCS-Bucket)
  logging: CLOUD_LOGGING_ONLY
