steps:
  # 1. Image mit eindeutigem Tag bauen (SHA ist immutable)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA', '.']

  # 2. Image pushen (nur der SHA-Tag ist erforderlich)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA']

  # 3. DEPLOY TO CLOUD RUN mit dem neuen Image-Tag (wichtig!)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy lion-astro-app \
          --image=gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA \
          --region=europe-west3 \
          --platform=managed \
          --quiet

# 4. Nur das SHA-Image registrieren (latest ist redundant)
images: ['gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET