steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/mein-web-app:$SHORT_SHA', '.']
images: ['gcr.io/$PROJECT_ID/mein-web-app:$SHORT_SHA']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
