steps:
  # 1. Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA', '.']

  # 2. Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud run deploy lion-astro-app \
          --image=gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA \
          --region=europe-west1 \
          --platform=managed \
          --quiet

images:
  - 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA'
