steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/myproject/myimage', '.']
    logging: CLOUD_LOGGING_ONLY
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA', '.'] # Korrekter Image Name 'lion-astro-app', aber noch Commit SHA Tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA', 'gcr.io/$PROJECT_ID/lion-astro-app:latest'] # Füge latest Tag hinzu
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lion-astro-app:latest'] # Pushe mit latest Tag

images: ['gcr.io/$PROJECT_ID/lion-astro-app:$SHORT_SHA', 'gcr.io/$PROJECT_ID/lion-astro-app:latest'] # Beides als Images angeben
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

